---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: slurmd
    {{ include "sok.labels" . | nindent 4 }}
  name: slurmd
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      component: slurmd
      {{ include "sok.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: slurmd
        {{ include "sok.labels" . | nindent 8 }}
      annotations:
        checksum/slurm-conf: {{ include (print $.Template.BasePath "/slurmconf.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: init
        image: ghcr.io/abatilo/sok/munge
        command:
        - sh
        - -c
        - |
          set -ex

          # munge prep
          chmod +t /run
          mkdir -p /run/munge
          chmod +t /run/munge
          chown -R 101:101 /run/munge

          # slurmd prep
          mkdir -p /var/log
          touch /var/log/slurmd.log
          chown -R 1000:1000 /var/log/

          mkdir -p /var/spool/slurmd
          chown -R 1000:1000 /var/spool/

        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /var
          name: var
      containers:
      - name: munge
        image: ghcr.io/abatilo/sok/munge
        securityContext:
          # Munge user
          runAsUser: 101
          runAsGroup: 101
        command:
        - "bash"
        - "-c"
        - |
          /usr/sbin/munged -F
        volumeMounts:
        - mountPath: /etc/slurm/slurm.conf
          name: slurm-conf
          subPath: slurm.conf
        - mountPath: /run
          name: run
      - name: slurmd
        image: ghcr.io/abatilo/sok/slurmd
        securityContext:
          privileged: true
        ports:
        - containerPort: 6818
        volumeMounts:
        - mountPath: /etc/slurm/slurm.conf
          name: slurm-conf
          subPath: slurm.conf
        - mountPath: /run
          name: run
        - mountPath: /var
          name: var
      hostname: slurmd
      volumes:
      - configMap:
          name: slurm-conf
        name: slurm-conf
      - emptyDir: {}
        name: run
      - emptyDir: {}
        name: var
