---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: slurmctld
    {{ include "sok.labels" . | nindent 4 }}
  name: slurmctld
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      component: slurmctld
      {{ include "sok.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: slurmctld
        {{ include "sok.labels" . | nindent 8 }}
      annotations:
        checksum/slurm-conf: {{ include (print $.Template.BasePath "/slurmconf.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: munged-ownership
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          set -ex
          mkdir -p /var/log
          touch /var/log/slurmctld.log

          mkdir -p /var/spool/slurmctld
          chown -R 1000:1000 /var/spool/slurmctld

          mkdir -p /run/munge
          chown -R 101:101 /run/munge
          chmod +t /run/munge
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /var
          name: var
      containers:
      - name: slurmctld
        image: ghcr.io/abatilo/sok/slurmctld
        ports:
        - containerPort: 6817
        volumeMounts:
        - mountPath: /etc/slurm/slurm.conf
          name: slurm-conf
          subPath: slurm.conf
        - mountPath: /run
          name: run
        - mountPath: /var
          name: var
      - name: munge
        image: ghcr.io/abatilo/sok/slurmctld
        command:
        - "/usr/sbin/munged"
        args:
        - "-F"
        - "-f"
        volumeMounts:
        - mountPath: /etc/slurm/slurm.conf
          name: slurm-conf
          subPath: slurm.conf
        - mountPath: /run
          name: run
      hostname: slurmctld
      volumes:
      - configMap:
          name: slurm-conf
        name: slurm-conf
      - emptyDir: {}
        name: run
      - emptyDir: {}
        name: var
