---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld
spec:
  revisionHistoryLimit: 1
  template:
    metadata:
    spec:
      hostname: slurmctld
      initContainers:
      - name: munged-ownership
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          chown -R 101:101 /run/munge
          chmod +t /run/munge
        volumeMounts:
        - name: run-munge
          mountPath: "/run/munge"
      containers:
      - name: slurmctld
        image: ghcr.io/abatilo/sok/slurmctld
        ports:
        - containerPort: 6817
        volumeMounts:
        - name: slurm-conf
          mountPath: "/etc/slurm/slurm.conf"
          subPath: slurm.conf
        - name: run-munge
          mountPath: "/run/munge"
        - name: var-spool
          mountPath: "/var/spool"
      volumes:
      - name: slurm-conf
        configMap:
          name: slurm-conf
      - name: run-munge
        emptyDir: {}
      - name: var-spool
        emptyDir: {}
