apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    component: slurmctld

components:
- ../conf

resources:
- deployment.yaml
- service.yaml
