on:
  schedule:
  # Every Sunday
  - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old tilt images
    strategy:
      fail-fast: false
      matrix:
        image-name:
        - "sok/slurmdbd"
        - "sok/slurmctld"
        - "sok/slurmd"
        - "sok/login"
    steps:
    - uses: snok/container-retention-policy@v3.0.0
      with:
        account: user
        token: ${{ github.token }}
        image-names: ${{ matrix.image-name }}
        image-tags: "tilt*"
        cut-off: 2d
        rust-log: DEBUG
