on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
  # Every Sunday
  - cron: "0 0 * * 0"

permissions:
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old tilt images
    strategy:
      fail-fast: false
      matrix:
        image-name:
        - "sok/slurmdbd"
        - "slurmdbd"
    steps:
    - uses: snok/container-retention-policy@v3.0.0
      with:
        account: user
        token: ${{ github.token }}
        image-names: ${{ matrix.image-name }}
        image-tags: "tilt*"  # target any image that has a tag starting with the word test or dev
        cut-off: 1w
        dry-run: true
        rust-log: DEBUG
