on:
  workflow_dispatch:
  schedule:
  # Every Sunday
  - cron: "0 0 * * 0"

permissions:
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
    - uses: snok/container-retention-policy@v3.0.0
      with:
        account: snok
        token: ${{ github.token }}
        image-names: |
            sok/slurm-builder
            sok/slurmdbd
            sok/slurmctld
            sok/slurmd
            sok/login
        image-tags: "tilt*"  # target any image that has a tag starting with the word test or dev
        cut-off: 1w
        dry-run: true
