name: "Build"
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.event_name == 'push' && 'main' || github.event.number }}
  cancel-in-progress: ${{ github.event_name == 'push' }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - if: github.event_name == 'push'
        uses: docker/bake-action@v5
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          push: true

      - if: github.event_name == 'pull_request'
        uses: docker/bake-action@v5
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          push: false
          set: |
            *.cache-to=
